### PR TITLE
Fix stochastic behavior and refactor tests to use unittest

### LINKED ISSUE #9: Strategies not working as designed/expected
Tournament results are showing no variation which implies that the stochastic strategies are not acting scholastically.  #8 fixes the classification but that is not sufficient as demonstrated:

The following create two instances of the `Random` player:

```python
>>> import axelrod as axl
>>> import axelrod_fortran as axlf
>>> random1 = axlf.Player("KRANDOMC")
>>> random2 = axlf.Player("KRANDOMC")
>>> random1.classifier["stochastic"], random2.classifier["stochastic"]
(True, True)
```

Playing a match with a given seed:

```python
>>> axl.seed(0)
>>> match = axl.Match((random1, random2), turns=5)
>>> match.play()
[(D, D), (D, D), (D, D), (D, D), (D, D)]
```

Playing with a different seed:

```python
>>> axl.seed(5)  # I have tried many seeds
>>> match = axl.Match((random1, random2), turns=5)
>>> match.play()
[(D, D), (D, D), (D, D), (D, D), (D, D)]
```

To confirm that the random player always returns `D`:

```python
>>> for _ in range(20):
>>>    assert axl.Action.D == random1.strategy(random1)
```

The following checks that `Player.strategy` is working correctly as far as this is concerned:

```python
>>> for _ in range(20):
>>>     assert 1 == random1.original_strategy(their_last_move=0, move_number=0, my_score=0, their_score=0, noise=0, my_last_move=0)
```

I also checked other functions and there are definitely some that return different values (potentially with different inputs), the following test  that tests if a strategy only ever plays 0 or 1, **fails** (lines 88 and 95 are the relevant additions):

```python

   61 def test_original_strategy():                                                                                                                   
   62     """                                                                                                                                         
   63     Test original strategy against all possible first 5 moves of a Match                                                                        
   64     """                                                                                                                                         
   65     actions_to_scores = {(0, 0): (3, 3), (0, 1): (0, 5),                                                                                        
   66                          (1, 0): (5, 0), (1, 1): (1, 1)}                                                                                        
   67     for strategy in all_strategies:                                                                                                             
+  68         all_actions = []                                                                                                                        
   69         for opponent_sequence in itertools.product((0, 1), repeat=5):                                                                           
   70                                                                                                                                                 
   71             player = Player(strategy)                                                                                                           
   72                                                                                                                                                 
   73             # Initial set up for empty history                                                                                                  
   74             my_score, their_score = 0, 0                                                                                                        
   75             move_number = 1                                                                                                                     
   76             their_previous_action, my_action = 0, 0                                                                                             
   77                                                                                                                                                 
   78             for action in opponent_sequence:                                                                                                    
   79                 my_action = player.original_strategy(                                                                                           
   80                     their_last_move=their_previous_action,                                                                                      
   81                     move_number=move_number,                                                                                                    
   82                     my_score=my_score,                                                                                                          
   83                     their_score=their_score,                                                                                                    
   84                     noise=0,                                                                                                                    
   85                     my_last_move=my_action)                                                                                                     
   86                                                                                                                                                 
   87                 assert my_action in [0, 1]                                                                                                      
+  88                 all_actions.append(my_action)                                                                                                   
   89                                                                                                                                                 
   90                 scores = actions_to_scores[my_action, action]                                                                                   
   91                 their_previous_action = action                                                                                                  
   92                 my_score += scores[0]                                                                                                           
   93                 their_score += scores[1]                                                                                                        
+  94                                                                                                                                                 
+  95         assert len(list(set(all_actions))) == 1  
```

### PR DESCRIPTION
**Pull request by marcharper**
Closes #9

### CODE REVIEW

**Comment by drvinceknight** [comment]
If I'm not mistaken this isn't quite using unittest correctly, that needs`self.assertEqual` etc as opposed to just `assert` for failures to be reported properly (otherwise you're not really using unittest).

**Comment by marcharper** [comment]
Fixed

**Comment by drvinceknight** [comment]
Nice!

@meatballs I'd suggest this goes in, once we're sure it's easy and straightforward for everyone/newcomers to run the tests with the pytest runner we can/should flip them back.

**Comment by meatballs** [comment]
I've reverted the shift to unittest and #13 has added some instructions on running pytest.

If those instructions still don't work for some reason, we'll come back and cherry pick the commits to move to unittest.

**Pull request merged**
