### PR TITLE
Random seeding

### PR DESCRIPTION
**Pull request by marcharper**
Do not merge, won't work until the random_seed branch of Axelrod is merged

~~I don't understand what ` test_champion_v_alternator` is doing.~~

### CODE REVIEW

**Comment by drvinceknight** [comment]
> don't understand what ` test_champion_v_alternator` is doing.

it's a specific regression test for https://github.com/Axelrod-Python/axelrod-fortran/issues/62 which was added in https://github.com/Axelrod-Python/axelrod-fortran/pull/63. It ensures this fix to `TourExec` works: https://github.com/Axelrod-Python/TourExec/pull/6/files

If I remember correctly there was an issue when `k61r` played repeatedly (which probably wasn't picked up in the original Axelrod tournaments as they were no repetitions so to speak).

**Comment by drvinceknight** [comment]
> EDIT: So I believe what it's doing is checking we get the same results when playing the match multiple times.

(But it's very poorly documented: that's my bad.)

**Comment by marcharper** [comment]
I believe I've fixed the test, which passes locally. But all the tests won't work here until we release a new version of `axelrod`.

**Comment by drvinceknight** [comment]
https://github.com/Axelrod-Python/Axelrod/pull/1288 has been merged: I plan to do a new release first thing tomorrow (Wednesday) morning.

**Comment by drvinceknight** [comment]
Looks good to me :+1: Once we have a new release I'll get the simulations going for the reproducing paper :+1:

**Comment by marcharper** [comment]
@meatballs PTAL. We should release a new version of axelrod-fortran after this PR goes in.

The CI checks don't show up for me on this page, you can see them passing [here](https://travis-ci.org/github/Axelrod-Python/axelrod-fortran).

**Comment by drvinceknight** [comment]
> The CI checks don't show up for me on this page, you can see them passing [here](https://travis-ci.org/github/Axelrod-Python/axelrod-fortran).

Could be worth moving this to GitHub actions? I could have a go at putting that together.

**Comment by marcharper** [comment]
Sorry I hit the request review from you @drvinceknight and cannot rescind it

**Review by drvinceknight — APPROVED** [review]
:+1:

**Pull request merged**
